package com.luis.urlShortener.model;

import jakarta.persistence.*;

/**
 * JPA entity representing a record in the "users" table.
 * Contains fields for ID, product name, and a numeric 'preso' value.
 * Used for persistence and data access within the application.
 */

@Entity
@Table(name = "users")
public class Model {

    /**
     * Unique identifier for the Model entity, automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name or description of the product associated with this Model.
     */
    private String produto;

    /**
     * Numeric value representing the 'preso' attribute; its meaning depends on business context.
     */
    private int preso;

    /**
     * Constructs a new Model instance with the specified 'preso' value and product name.
     *
     * @param preso   the numeric value representing the 'preso' attribute
     * @param produto the name or description of the product
     */
    public Model(int preso, String produto) {
        this.preso = preso;
        this.produto = produto;
    }

    /**
     * Default constructor required by JPA.
     * Allows the framework to instantiate the entity without setting initial values.
     */
    public Model() {
    }

    /**
     * Returns the unique identifier of the Model.
     *
     * @return the ID of the entity
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the Model.
     *
     * @param id the ID to assign to the entity
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the 'preso' value of the Model.
     *
     * @return the numeric 'preso' value
     */
    public int getPreso() {
        return preso;
    }

    /**
     * Sets the 'preso' value of the Model.
     *
     * @param preso the value to assign to the 'preso' field
     */
    public void setPreso(int preso) {
        this.preso = preso;
    }

    /**
     * Returns the product name associated with the Model.
     *
     * @return the product name
     */
    public String getProduto() {
        return produto;
    }

    /**
     * Sets the product name associated with the Model.
     *
     * @param produto the name to assign to the product field
     */
    public void setProduto(String produto) {
        this.produto = produto;
    }



}
